@startuml

start
:user enters list command;
:identify parameter of list command;
if () then ([no parameter])
    :display all persons;
else ([invalid parameter])
    :display "invalid command" message;
endif
if (is a Type?) then (yes)
    :update list to show
        all patients;
elseif (is donor?) then (yes)
    :update list to show
        all donors;
elseif (is doctor?) then (yes)
    :update list to show
          all doctors;
else (invalid parameter)
    :display error message;
endif
stop
@enduml
