= Chow Jia Ying - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: ORGANice

== Overview
This document is written to document my role and contributions to ORGANice. It is a team project developed
for the module CS2103T, the introductory Software Engineering module in NUS.

=== About the team
We are a group of 5 Year 2 Computer Science undergraduates.

=== About ORGANice
ORGANice is an organ matching desktop application designed for hospital administration staff who prefer typing. +

It is morphed from Address Book 3, which is a desktop application used for teaching Software Engineering principles.
The user interacts with it using a Command Line Interface (CLI), and it has a GUI created with JavaFX.
It is written in Java, and has about 10,000 lines of code (LoC).

=== Formatting used in this document
Words highlighted in grey refers to technical terms in this application.


== Summary of contributions

* *Major enhancement*: added the ability to match patients and donors
//this portion will be changed
** What it does: This feature identifies a list of potential matches between patients and organ donors.
** Justification: This feature allows users to find potential donors for patients in a hospital efficiently.
//tutor said don't use 'affects' but i'm struggling to think of another word rn.
** Highlights: The addition of this feature affects commands to be added in future.
It required an in-depth analysis of design alternatives.
The implementation too was challenging as it required an understanding of how to change the list
displayed in Address Book 3.

* *Minor enhancement*: refactored Person class to the Patient class.

* *Minor enhancement*: added coloured tags to each person in the person list.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Created issues to keep track of work to be done.
*** Arranged for system and acceptance testing.
** Enhancements to existing features:
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
*** Refactored code to improve code quality
*** Implemented logging features
*** Fixed bugs
** Documentation:
*** Authored the 'Introduction', 'Quick Start', 'Components of ORGANice' and
'Detecting matches' sub-sections in the 'Features' section
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])

== Contributions to the User Guide
This section documents my contributions to the User Guide. I authored the following sections:

* Introduction
* Quick Start
* Components of ORGANice
* 'Detecting matches' in the 'Features' section

Given below are excerpts of my contribution to the User Guide.

{Start of extract from User Guide}

include::../UserGuide.adoc[tag=intro]

include::../UserGuide.adoc[tag=match]
{End of extract from User Guide}

== Contributions to the Developer Guide
This section documents my contributions to the Developer Guide. I authored the following sections:

* Introduction
* Setting up
* 'Matching feature' sub-section in the 'Implementation' section

Given below are excerpts of my contribution to the Developer Guide.

{Start of extract from Developer Guide}
include::../DeveloperGuide.adoc[tag=matching]
{End of extract from Developer Guide}
