= Yen Peng - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project Portfolio for ORGANice
---
This project portfolio details my main contributions towards the development of a team project called ORGANice.

== 1. Overview

This section briefly describes what ORGANice is and the team behind it, followed by an explanation of the formatting used in this document.

=== 1.1 About ORGANice

ORGANice is a Command Line Interface (CLI) desktop application, meaning that user interaction is mainly through typing in commands.
This application is targeted at hospital administrators and its main features include storing hospital information,
finding compatible donors for patients awaiting organ transplants, and following up on administrative matters related to the organ matching process.

ORGANice is the product of a software engineering project done by a team of 5 students, including myself, who are second-year Computer Science students from the National University of Singapore (NUS).
Under a two-month-long time frame, we conceptualised ORGANice and moulded it from an existing application, known as "Address Book", that stores and manages people's contact information.
For the languages used, ORGANice is written in Java while its Graphical User Interface (GUI) is written in JavaFX.

=== 1.2 Formatting Used

Words that are highlighted in grey are technical terms used in this software engineering project.

== 2. Summary of Contributions

This section elaborates on the enhancements I did to ORGANice.

* *Major enhancement*: Added the ability to sort matches according to different criteria.
** What it does: Allows the user to sort patient-donor pairs according to compatibility rate, priority of the patient, or donor's organ expiry date.
** Justification: Helps the hospital to make more informed decisions after knowing which pairs are the most compatible, which patient to prioritize, and which organs are expiring soon respectively.
** Highlights: Can add in more sorting options as future enhancements. The implementation is slightly challenging as it took into consideration how the match feature is implemented.

* *Minor enhancement*: Added a list feature that allows the user to list down all persons or persons of a specified type in ORGANice.

* *Minor enhancement*: Added an organ class to ORGANice.

* *Minor enhancement*: Designed the logo of ORGANice, and updated the application window to display title and logo.

* *Code contributed*: [https://nus-cs2103-ay1920s1.github.io/tp-dashboard/#search=Yen-Peng&sort=groupTitle&sortWithin=title&since=2019-09-06&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=Yen-Peng&tabRepo=AY1920S1-CS2103T-T13-1%2Fmain%5Bmaster%5D[RepoSense]]

* *Other contributions*:
** Documentation:
*** Updated the About Us page of ORGANice: https://github.com/AY1920S1-CS2103T-T13-1/main/commit/de6675c93eefa808ab11327910b64fb44853fa03[#11]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

Start of excerpt:

include::../UserGuide.adoc[tag=edit]

include::../UserGuide.adoc[tag=list]

include::../UserGuide.adoc[tag=sort]

include::../UserGuide.adoc[tag=help]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=modeldiagram]

include::../DeveloperGuide.adoc[tag=list]

include::../DeveloperGuide.adoc[tag=sort]

include::../DeveloperGuide.adoc[tag=usecaselist]

include::../DeveloperGuide.adoc[tag=usecasesort]
